version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_almacen
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""     # contraseña vacía
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: almacen      # base creada automáticamente
    ports:
      - "3306:3306"               # acceder desde localhost:3306
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
